/*
 * File: app/view/mainNavView.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fb_display.view.mainNavView', {
    extend: 'Ext.navigation.View',

    config: {
        id: 'mainNavView',
        styleHtmlContent: true,
        ui: '',
        items: [
            {
                xtype: 'panel',
                html: '<div class="fb-login-button" data-show-faces="true" data-width="100" data-max-rows="1"></div>',
                id: 'loginPanel',
                style: 'background-color: #fee',
                styleHtmlContent: true,
                items: [
                    {
                        xtype: 'button',
                        action: 'goHome',
                        id: 'homeBtn',
                        itemId: 'homeBtn',
                        text: 'Home'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onHomeBtnTap',
                event: 'tap',
                delegate: '#homeBtn'
            }
        ]
    },

    onHomeBtnTap: function(button, e, eOpts) {
        this.push(Ext.create('fb_display.view.MyTabPanel'), { 
            title: "tabPanel"
        });
    }

});