/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('fb_display.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',

    config: {
        id: 'tabPanel',
        items: [
            {
                xtype: 'container',
                title: 'Home',
                id: 'homeTab',
                itemId: 'HomeTab',
                items: [
                    {
                        xtype: 'image',
                        height: 201,
                        src: 'https://graph.facebook.com/duchuy.luu/picture'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Tab 2'
            },
            {
                xtype: 'container',
                title: 'Tab 3'
            }
        ]
    }

});